### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by emilwojtaszek** [oovoodev/iOS-SDK-Sample#12]
```
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(bands.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(celt.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(celt_encoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(celt_decoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(cwrs.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(entcode.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(entdec.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(entenc.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(kiss_fft.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(laplace.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(mathops.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(mdct.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(modes.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(pitch.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(celt_lpc.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(quant_bands.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(rate.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(vq.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(armcpu.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(arm_celt_map.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(celt_neon_intr.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(CNG.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(code_signs.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(init_decoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_core.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_frame.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_parameters.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_indices.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_pulses.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decoder_set_fs.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(dec_API.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(enc_API.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(encode_indices.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(encode_pulses.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(gain_quant.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(interpolate.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LP_variable_cutoff.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_decode.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NSQ.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NSQ_del_dec.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(PLC.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(shell_coder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_gain.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_LTP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_NLSF_CB_NB_MB.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_NLSF_CB_WB.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_other.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_pitch_lag.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(tables_pulses_per_block.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(VAD.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(control_audio_bandwidth.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(quant_LTP_gains.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(VQ_WMat_EC.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(HP_variable_cutoff.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_encode.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_VQ.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_unpack.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_del_dec_quant.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(process_NLSFs.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_LR_to_MS.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_MS_to_LR.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(check_control_input.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(control_SNR.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(init_encoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(control_codec.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(A2NLSF.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(ana_filt_bank_1.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(biquad_alt.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(bwexpander_32.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(bwexpander.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(debug.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(decode_pitch.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(inner_prod_aligned.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(lin2log.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(log2lin.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LPC_analysis_filter.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LPC_inv_pred_gain.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(table_LSF_cos.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF2A.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_stabilize.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(NLSF_VQ_weights_laroia.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(pitch_est_tables.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_down2_3.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_down2.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_private_AR2.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_private_down_FIR.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_private_IIR_FIR.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_private_up2_HQ.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(resampler_rom.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(sigm_Q15.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(sort.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(sum_sqr_shift.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_decode_pred.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_encode_pred.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_find_predictor.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(stereo_quant_pred.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(apply_sine_window_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(corrMatrix_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(encode_frame_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(find_LPC_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(find_LTP_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(find_pitch_lags_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(find_pred_coefs_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LPC_analysis_filter_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LTP_analysis_filter_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LTP_scale_ctrl_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(noise_shape_analysis_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(prefilter_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(process_gains_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(regularize_correlations_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(residual_energy_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(solve_LS_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(warped_autocorrelation_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(wrappers_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(autocorrelation_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(burg_modified_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(bwexpander_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(energy_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(inner_product_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(k2a_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(levinsondurbin_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(LPC_inv_pred_gain_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(pitch_analysis_core_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(scale_copy_vector_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(scale_vector_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(schur_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(sort_FLP.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus_decoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus_encoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus_multistream.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus_multistream_encoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(opus_multistream_decoder.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(repacketizer.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(analysis.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(mlp.o)
warning: ignoring debug info with an invalid version (600056001) in /Users/emil/Documents/Projects/ios/gistr-ios/Frameworks/ooVooSDK-iOS.framework/ooVooSDK-iOS(mlp_data.o)
Undefined symbols for architecture arm64:
  "_llvm.arm64.neon.faddp.v2f32", referenced from:
      _celt_pitch_xcorr_float_neon in ooVooSDK-iOS(celt_neon_intr.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


```

How can i fix it? This appear after moving to Xcode 6.3

**Comment by jerrypainter** [comment]
same problem here. How can I fix it?

**Comment by emilwojtaszek** [comment]
They've sent me the newest library which fixed all problems

**Comment by jerrypainter** [comment]
Is the newest one that they will release soon?

**Comment by bick111** [comment]
Hey emilwojtaszek can you provide me dropbox link for latest oovoo SDK with 64 bit support. 
Thankyou in advance.

**Comment by emilwojtaszek** [comment]
https://www.dropbox.com/sh/thf9e94npahmkh3/AAAIael2dAFKsTnkD5jA3N_Va?dl=0

**Comment by bick111** [comment]
Thanks a lot man! Let me try it. :)

**Comment by eakraly** [comment]
Latest SDK version is available on developer.oovoo.com and it fixes the linkage issue. Other warnings are coming from third party components compiled by older version of XCode. This warnings basically say that you will not be able to OPUS audio codec library - which, I suppose, you would not do anyway.

**Comment by bick111** [comment]
Undefined symbols for architecture arm64:

  "_llvm.aarch64.neon.addp.v2f32", referenced from:

      _celt_pitch_xcorr_float_neon in ooVooSDK-iOS(celt_neon_intr.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see
invocation)


I am using Xcode 6.1, Still not able to link successfully

**Comment by eakraly** [comment]
Is there any specific reason why you use XCode 6.1, @bick111 ? Im not sure this is the issue but I'm absolutely sure it works on XCode 6.3.2 and 7.0.

**Comment by mydoal** [comment]
Has anyone found a solution for this?
The sample app from oovoosdk-ios-2.0.0.67 will not link under XCode 6.1.
Any help is much appreciated.
